name: Telegram Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4  # Actualizado a v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install python-telegram-bot
          pip install telethon


      - name: Run python main.py
        run: python .github/workflows/main.py
        

        